$(function(){
    $('form').submit(function(){
        //名前の取得
        console.log("お名前は"+$('#name').val()+"です。");
        //性別の取得
        console.log("性別は"+$('input[name=sex]:checked').val()+"です。");
        //注文する商品の取得
        console.log("注文する商品は"+$('#items').val()+"です。");
        //配送時間希望の取得
        console.log("配送時間希望は"+$('#time').val()+"です。");
        //特記事項の取得
        console.log("特記事項:\n"+$('#notice').val());
    });
});